// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tztlaqoiuxonwyyrgpmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6dGxhcW9pdXhvbnd5eXJncG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDkwMjgsImV4cCI6MjA2NDE4NTAyOH0.E09o3rbyI3Gsc1sVsZp3FwaOyEqSngB2m7WHyQ4jQYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);